---
# https://github.com/marketplace/actions/kaniko-action

name: Build docker images
on:
  push: {}
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     include:
    #       - FROM_TAG: "23.04"
    #       - FROM_TAG: ""
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo tag=${FROM_TAG} ref=$GITHUB_REF_NAME env=$MY_ENV_VAR
        env:
          FROM_TAG: ${{ env.GITHUB_REF_NAME == 'main' && '' || env.GITHUB_REF_NAME }}
          MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}

      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
          build-args: |
            FROM_TAG=${{ env.GITHUB_REF_NAME == 'main' && '' || env.GITHUB_REF_NAME }}

