---
# https://github.com/marketplace/actions/kaniko-action

name: Build docker images
on:
  push: {}
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     include:
    #       - FROM_TAG: "23.04"
    #       - FROM_TAG: ""
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - run: echo $DO
        env:
          DO: ${{ steps.metadata.outputs.version }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - run: echo tag=${FROM_TAG} ref=$GITHUB_REF_NAME env=$MY_ENV_VAR env2=$MY_ENV_VAR2 env3=$MY_ENV_VAR3
      #   env:
      #     FROM_TAG: ${{ env.GITHUB_REF_NAME == '23.04' && github.env.GITHUB_REF_NAME || '2' }}
      #     MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}
      #     MY_ENV_VAR2: ${{ github.ref == 'refs/heads/main' && '' || 'value_for_other_branches' }}
      #     MY_ENV_VAR3: ${{ github.ref == 'refs/heads/main' && '' || github.env.GITHUB_REF_NAME }}
      # - run: echo from_tag=${FROM_TAG} tag=$
      #   env:
      #     TAG: ${{ env.FROM_TAG == '' && 'latest' || '' }}
      #     MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}
      #     MY_ENV_VAR2: ${{ github.ref == 'refs/heads/main' && '' || 'value_for_other_branches' }}
      #     MY_ENV_VAR3: ${{ github.ref == 'refs/heads/main' && '' || github.env.GITHUB_REF_NAME }}

      # - run: |
      #     if [ "$GITHUB_REF_NAME" == "main" ] ; then
      #       echo "tag=''" >> "$GITHUB_OUTPUT"
      #     else
      #       echo "tag=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
      #     fi
      #   id: setup_tag

      # - run: echo $TAG
      #   env:
      #     TAG: ${{ steps.setup_tag.outputs.tag }}

      # - uses: int128/kaniko-action@v1
      #   with:
      #     push: true
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     labels: ${{ steps.metadata.outputs.labels }}
      #     cache: true
      #     cache-repository: ghcr.io/${{ github.repository }}/cache
      #     build-args: |
      #       FROM_TAG=${{ env.GITHUB_REF_NAME == 'main' && '' || env.GITHUB_REF_NAME }}
